"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Instruction = void 0;
var Instruction;
(function (Instruction) {
    Instruction[Instruction["Heartbeat"] = 0] = "Heartbeat";
    Instruction[Instruction["Handshake"] = 1] = "Handshake";
    Instruction[Instruction["PeerConnect"] = 2] = "PeerConnect";
    Instruction[Instruction["PeerDisconnect"] = 3] = "PeerDisconnect";
    Instruction[Instruction["AreaSubscribe"] = 4] = "AreaSubscribe";
    Instruction[Instruction["AreaUnsubscribe"] = 5] = "AreaUnsubscribe";
    Instruction[Instruction["GlobalMessage"] = 6] = "GlobalMessage";
    Instruction[Instruction["LocalMessage"] = 7] = "LocalMessage";
    Instruction[Instruction["RecordCreate"] = 8] = "RecordCreate";
    Instruction[Instruction["RecordRead"] = 9] = "RecordRead";
    Instruction[Instruction["RecordUpdate"] = 10] = "RecordUpdate";
    Instruction[Instruction["RecordDelete"] = 11] = "RecordDelete";
    Instruction[Instruction["RecordReply"] = 12] = "RecordReply";
    Instruction[Instruction["Unknown"] = 255] = "Unknown";
})(Instruction = exports.Instruction || (exports.Instruction = {}));
