"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Replication = void 0;
var Replication;
(function (Replication) {
    Replication[Replication["ExceptSelf"] = 0] = "ExceptSelf";
    Replication[Replication["IncludingSelf"] = 1] = "IncludingSelf";
    Replication[Replication["OnlySelf"] = 2] = "OnlySelf";
})(Replication = exports.Replication || (exports.Replication = {}));
